apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-multicluster
  namespace: argocd

spec:
  generators:
  - clusters: {}

  template:
    metadata:
      name: '{{name}}-nginx'

    spec:
      project: default

      source:
        repoURL: https://github.com/<your-github-user>/gitops-demo.git
        targetRevision: HEAD
        path: apps/nginx

      destination:
        server: '{{server}}'
        namespace: nginx

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
        - CreateNamespace=true
